name: Pull Docker Images
description: Composite task to pull docker images

inputs:
  platform:
    description: The platform (amd64/arm64)
    required: true
  ghcr-username:
    description: GitHub Container Registry username
    required: true
  ghcr-token:
    description: GitHub Container Registry token
    required: true

runs:
  using: composite
  steps:
  - name: Login to GitHub Container Registry
    uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
    with:
      registry: ghcr.io
      username: ${{ inputs.ghcr-username }}
      password: ${{ inputs.ghcr-token }}
  - name: Download digests
    uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
    with:
      path: /tmp/digests
      pattern: docker-digests-${{ inputs.platform }}-*
      merge-multiple: true
  - name: Pull docker images
    shell: bash
    run: |
      DOCKER_PREFIX=ghcr.io/${{ github.repository }}
      DOCKER_PREFIX=$(echo $DOCKER_PREFIX | tr '[A-Z]' '[a-z]')
      for TARGET in worker database-migration
      do
        digests=(/tmp/digests/"$TARGET"/*)
        digest=$(basename $digests)
        echo "Pulling $TARGET (sha256:$digest) image"
        docker pull "$DOCKER_PREFIX/$TARGET@sha256:${digest}"
        docker tag "$DOCKER_PREFIX/$TARGET@sha256:${digest}" brickcatalog/$TARGET
      done
