import 'server-only';

import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import { I18nProvider } from '@/components/i18n/I18nProvider';
import { getLanguage } from '@/lib/translate';
import { getBaseUrl } from '@/lib/url';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  const language = await getLanguage();

  return (
    <html
      data-base-url={getBaseUrl().toString()}
      lang={language}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider language={language}>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
