apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brick-catalog

commonLabels:
  app.kubernetes.io/part-of: brick-catalog

resources:
- namespace.yaml
- database
- next
- worker
- database-migration
