name: Build and Test Docker
on:
  workflow_call:
    inputs:
      platform:
        type: string
        required: true

jobs:
  build:
    name: 'Build: ${{ matrix.target }}'
    runs-on: ${{ inputs.platform == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        target: [ worker, database-migration ]
    steps:
      # https://github.com/actions/virtual-environments/issues/1187
      - name: Tune linux network
        run: sudo ethtool -K eth0 tx off rx off
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate image name
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ matrix.target }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> "$GITHUB_ENV"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ${{ env.IMAGE_ID }}
          bake-target: ${{ matrix.target }}
