name: Test
on:
  workflow_call:

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Setup Node.js env
        uses: ./.github/actions/setup-node-env
        with:
          cache-key: test
      - name: Setup playwright
        # install chromium including system dependencies and without headless shell (we use the real browser in headless mode)
        run: pnpm dlx playwright install chromium --with-deps --no-shell
      - name: Run Test
        run: pnpm run test
